version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kbeye
      POSTGRES_USER: kbeye
      POSTGRES_PASSWORD: kbeye_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kbeye"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: